# buildspec-dev.yml
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo "PREBUILD"

  build:
    commands:
      - cd compose && docker-compose -f docker-compose-common.yml -f docker-compose-development.yml build

  post_build:
    commands:
      - aws s3 sync s3://d941fa982d745-images/dev/$ENVKEY
