userdb:
  host: mydbinstance.csvkmjl9r9hs.ap-northeast-1.rds.amazonaws.com
  dbname: mydbinstance
  user: admin
  password: hogehoge

logdb:
  host: postgresql
  dbname: logdb
  user: root
  password: hogehoge

redis:
  host: redis

dynamodb:
  endpoint: http://dynamodb.ap-northeast-1.amazonaws.com
  region: ap-northeast-1
  key:
  secret:
  table: mydynamo

storage:
  endpoint: http://storage:9000
  region: ap-northeast-1
  key: minio
  secret: miniminio
  bucket: dummy
